### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by jswang1973** [opennetworklinux/ONL#115]
Hi OS 
$ uname -a
Linux opennetworkLinux 3.16.0-41-generic #57~14.04.1-Ubuntu SMP Thu Jun 18 18:01:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

When performing steps from docs at:
http://opennetlinux.org/docs/build

     Build ONL Summary
      #> git clone git://github.com/opennetworklinux/ONL
      #> cd ONL
      #> make docker                                              # enter the docker workspace
      root@8onl-builder:/path/to/ONL# make onl-x86 onl-powerpc    # build both x86 and PPC images

Would  you give some advice!!
Thank you

//=============================================================
//=============================================================
WARNING:onlpkg:no matching packages for onlp (powerpc)
INFO:onlpkg:can be built locally at /home/switch/OpenNetworkLinux/ONL/components/powerpc/ofdpa-2.0-closed
make[2]: Entering directory `/home/switch/OpenNetworkLinux/ONL/components/powerpc/ofdpa-2.0-closed'
rm -rf /home/switch/OpenNetworkLinux/ONL/components/any/ofdpa-2.0-closed/deb/debuild-powerpc
cp -R /home/switch/OpenNetworkLinux/ONL/components/any/ofdpa-2.0-closed/deb/debuild /home/switch/OpenNetworkLinux/ONL/components/any/ofdpa-2.0-closed/deb/debuild-powerpc
make -C /home/switch/OpenNetworkLinux/ONL/components/any/ofdpa-2.0-closed deb DEBUILD_DIR=debuild-powerpc
make[3]: Entering directory `/home/switch/OpenNetworkLinux/ONL/components/any/ofdpa-2.0-closed'
make -C deb
make[7]: warning: -jN forced in submake: disabling jobserver mode.
make -C /home/switch/OpenNetworkLinux/ONL/submodules/ofdpa-2.0-closed
make[8]: *** No targets specified and no makefile found.  Stop.
make[7]: *** [alltargets] Error 2
make[6]: *** [component] Error 2
make[5]: *** [deb] Error 2
make[4]: *** [deb] Error 2
make[3]: *** [deb] Error 2
make[3]: Leaving directory `/home/switch/OpenNetworkLinux/ONL/components/any/ofdpa-2.0-closed'
make[2]: *** [deb] Error 2
make[2]: Leaving directory `/home/switch/OpenNetworkLinux/ONL/components/powerpc/ofdpa-2.0-closed'
Traceback (most recent call last):
  File "/home/switch/OpenNetworkLinux/ONL/tools/onlpkg.py", line 289, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/switch/OpenNetworkLinux/ONL/tools/onlpkg.py", line 159, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/switch/OpenNetworkLinux/ONL/components/powerpc/ofdpa-2.0-closed', 'deb')' returned non-zero exit status 2
make[1]: *** [component-deps] Error 1
make[1]: Leaving directory `/home/switch/OpenNetworkLinux/ONL/builds/components'
make: *** [all-components] Error 2
//=============================================================
//=============================================================

**Comment by capveg** [comment]
Hi,

Thanks for reporting this issue.  It's actually a problem caused by the way
the new OpenFlow and OF-DPA packages are built.  Previously on the list
I've been giving folks instructions on how to work around it, but since I'm
on vacation now, I had time to fix this more properly.

I've just merged in code to autodownload the ofdpa-2.0-closed package with
https://github.com/opennetworklinux/ONL/pull/116

So now the build should work for you.  Please `git pull` to get the latest
code and try it again.

Thanks,

- Rob
.

**Comment by jswang1973** [comment]
Hi Rob
thank you very much
I am going to rebuild it after reading your suggestion.
