### ISSUE TITLE
submodule ofdpa-closed Permission denied (Public Key) - ONL build (make onl-powerpc in docker)

### ISSUE THREAD

**Issue by ahmedcs** [opennetworklinux/ONL#123]
I get the following error while building ONL

WARNING:onlpkg:no matching packages for ofdpa-2.0-closed (powerpc)
INFO:onlpkg:can be built locally at /home/ahmed/ONL/components/powerpc/ofdpa-2.0-closed
make[4]: Entering directory `/home/ahmed/ONL/components/powerpc/ofdpa-2.0-closed'
rm -rf /home/ahmed/ONL/components/any/ofdpa-2.0-closed/deb/debuild-powerpc
cp -R /home/ahmed/ONL/components/any/ofdpa-2.0-closed/deb/debuild /home/ahmed/ONL/components/any/ofdpa-2.0-closed/deb/debuild-powerpc
make -C /home/ahmed/ONL/components/any/ofdpa-2.0-closed deb DEBUILD_DIR=debuild-powerpc
make[5]: Entering directory `/home/ahmed/ONL/components/any/ofdpa-2.0-closed'
Submodule 'submodules/ofdpa-2.0-closed' (git@github.com:opennetworklinux/ofdpa-2.0-closed) registered for path 'submodules/ofdpa-2.0-closed'
Cloning into 'submodules/ofdpa-2.0-closed'...
The authenticity of host 'github.com (192.30.252.130)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:opennetworklinux/ofdpa-2.0-closed' into submodule path 'submodules/ofdpa-2.0-closed' failed
Traceback (most recent call last):
  File "/home/ahmed/ONL/tools/submodules.py", line 100, in <module>
    submodule_update(module, os.getenv("SUBMODULE_DEPTH"))
  File "/home/ahmed/ONL/tools/submodules.py", line 59, in submodule_update
    if subprocess.check_call(args) != 0:
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', 'submodules/ofdpa-2.0-closed']' returned non-zero exit status 1
make[5]: *** [component-deps] Error 1
make[5]: Leaving directory `/home/ahmed/ONL/components/any/ofdpa-2.0-closed'
make[4]: *** [deb] Error 2
make[4]: Leaving directory `/home/ahmed/ONL/components/powerpc/ofdpa-2.0-closed'
Traceback (most recent call last):
  File "/home/ahmed/ONL/tools/onlpkg.py", line 291, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/ahmed/ONL/tools/onlpkg.py", line 161, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/ahmed/ONL/components/powerpc/ofdpa-2.0-closed', 'deb')' returned non-zero exit status 2
make[3]: *** [component-deps] Error 1
make[3]: Leaving directory `/home/ahmed/ONL/components/any/indigo-ofdpa-ofagent'
make[2]: *** [deb] Error 2
make[2]: Leaving directory `/home/ahmed/ONL/components/powerpc/indigo-ofdpa-ofagent'
Traceback (most recent call last):
  File "/home/ahmed/ONL/tools/onlpkg.py", line 291, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/ahmed/ONL/tools/onlpkg.py", line 161, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/ahmed/ONL/components/powerpc/indigo-ofdpa-ofagent', 'deb')' returned non-zero exit status 2
make[1]: *** [component-deps] Error 1
make[1]: Leaving directory `/home/ahmed/ONL/builds/components'
make: *** [all-components] Error 2

when i retry make onl-powerpc for the third time, it proceeds but later on gives this error

cd debuild-powerpc; debuild --prepend-path=/usr/lib/ccache -eONL -eBUILD_DIR_BASE  -apowerpc -b -us -uc
/bin/bash: line 0: cd: debuild-powerpc: No such file or directory
debuild: fatal error at line 629:
cannot find readable debian/changelog anywhere!
Are you in the source code tree?
make[8]: *** [deb] Error 255
make[7]: *** [deb] Error 2
make[6]: *** [deb] Error 2
make[6]: Leaving directory `/home/ahmed/ONL/components/powerpc/linux/kernel-85xx'
Traceback (most recent call last):
  File "/home/ahmed/ONL/tools/onlpkg.py", line 291, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/ahmed/ONL/tools/onlpkg.py", line 161, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/ahmed/ONL/components/powerpc/linux/kernel-85xx', 'deb')' returned non-zero exit status 2
make[5]: *** [component-deps] Error 1
make[5]: Leaving directory `/home/ahmed/ONL/components/any/ofdpa-2.0-closed'
make[4]: *** [deb] Error 2
make[4]: Leaving directory `/home/ahmed/ONL/components/powerpc/ofdpa-2.0-closed'
Traceback (most recent call last):
  File "/home/ahmed/ONL/tools/onlpkg.py", line 291, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/ahmed/ONL/tools/onlpkg.py", line 161, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/ahmed/ONL/components/powerpc/ofdpa-2.0-closed', 'deb')' returned non-zero exit status 2
make[3]: *** [component-deps] Error 1
make[3]: Leaving directory `/home/ahmed/ONL/components/any/indigo-ofdpa-ofagent'
make[2]: *** [deb] Error 2
make[2]: Leaving directory `/home/ahmed/ONL/components/powerpc/indigo-ofdpa-ofagent'
Traceback (most recent call last):
  File "/home/ahmed/ONL/tools/onlpkg.py", line 291, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/ahmed/ONL/tools/onlpkg.py", line 161, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/ahmed/ONL/components/powerpc/indigo-ofdpa-ofagent', 'deb')' returned non-zero exit status 2
make[1]: *** [component-deps] Error 1
make[1]: Leaving directory `/home/ahmed/ONL/builds/components'
make: *** [all-components] Error 2

which is again related to the ofdpa-closed

**Comment by capveg** [comment]
Ah -- thanks for the report.  I think I've found the problem and have fixed it: https://github.com/opennetworklinux/ONL/pull/125

Please try to update to the new HEAD and try again.
