### ISSUE TITLE
orc_brcm.so driver is not working for Edge-Core AS4600-54T-r0

### ISSUE THREAD

**Issue by ahmedcs** [opennetworklinux/ONL#126]
I believe the driver either old version or not working with the new Edge-Core (Accton) switch AS4600-54T-r0 using Broadcom Apollo2 Switching Chip.

I have done some debugging and believe probably this is the cause of issue #120 

On ONL website it is mentioned that this switch is tested and supported, maybe that is the case for the platform AS4600-54T but i am not sure if that is the case for AS4600-54T-r0.

Could someone verify this, as the switch does not have any hardware issues (tried PicOS and forwarding works perfectly).

Thanks

**Comment by capveg** [comment]
This should be fixed now - please retest if you have a chance.

**Comment by giantbull** [comment]
where can get the orc_brcm driver for orc? 

thanks
