### ISSUE TITLE
L2 flood and learn forwarding in ORC/ONL

### ISSUE THREAD

**Issue by soramichi** [opennetworklinux/ONL#127]
Hello,

I'm trying ORC/ONL on a Quanta LY2 connecting two servers with 1G-eth fibers.

    [server]--fiber--[ONL Quanta LY2]--fiber--[server]

L3 routing using Quagga works perfectly (cool!) with hardware offloading enabled (confirmed no packets escalated to LY2 CPU),
but I couldn't see how to make L2 flood and learn forwarding work on ORC/ONL.

The thing is that CONFIG_BRIDGE is neither 'y' nor 'm' in ONL thus a linux bridge cannot be created,
which makes it impossible to set up ONL like a software switch using normal Linux server.

    root@onl-powerpc:~# zcat < /proc/config.gz  | grep BRIDGE
    # CONFIG_BRIDGE is not set

Could someone please tell us how to set up ONL as a L2 flood and learn switch?

Thanks.

**Comment by capveg** [comment]
ORC by design does only L3 forwarding and not L2.  If you want to implement some of the L2 functionality, please take a look at the OF-DPA code - I believe all of the knobs are exposed to do so, but for better or for worse, this is working as expected.

**Comment by soramichi** [comment]
Hello Rob, thank you very much for the quick response.
We will check out the ofdpa.
