### ISSUE TITLE
client_flowtable_dump doesn't parse ipv6 flows correctly

### ISSUE THREAD

**Issue by capveg** [opennetworklinux/ONL#129]
When I have a correct IPv6 entry inserted into the UNICAST_ROUTING table, `client_flowtable_dump` formats it as IPv4 and outputs all zeros:

```
Table ID 30 (Unicast Routing):   Retrieving all entries. Max entries = 90112, Current entries = 1.
-- etherType = 0x86dd vrf:mask = 0x0000:0x0000 dstIp4 = 0.0.0.0/0.0.0.0 dstIp6 = 0.0.0.0/0.0.0.0 | GoTo = 60 (ACL Policy) groupId = 0x20000001 | priority = 1000 hard_time = 0 idle_time = 0 cookie = 645
```

Even though the client_routing program shows it has the correct state:

```
root@onl-powerpc:~# client_routing list --count=0 --ether=0x86dd --dstip6 ::
Listing up to 0 Unicast Routing flows.
Flow number 1.
Ethertype                = 0x86dd
Destination IPv6 address = fe80::2420:52ff:fe8f:5190
Destination IPv6 netmask = ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
 Actions:
Set output group ID = 0x20000001
Idle Time             = 0
```

**Comment by bhavishkhatri** [comment]
It looks like the void printUnicastRoutingFlow(ofdpaFlowEntry_t *flow) function in client_flowtable_dump.c is calling inet_ntop incorrectly.

It sets up a buffer of 20 bytes which is not enough for an IPv6 address.
   char addrBuf[20];

According to the usage notes for inet_ntop, the caller should use either of the following as defined in inet.h to allocate sufficient space for the result.

 51 #define INET_ADDRSTRLEN         (16)
 52 #define INET6_ADDRSTRLEN        (48)

The function calls below will fail:
  inet_ntop(AF_INET6, &match->dstIp6, addrBuf, sizeof(addrBuf));
  inet_ntop(AF_INET6, &match->dstIp6Mask, addrMaskBuf, sizeof(addrMaskBuf));

inet will return null but this is not tested here. The buffer (I'm guessing) remains unchanged showing us IPv4 like output.

How to correct:
add to includes:
#include <arpa/inet.h>

Modify the function to include the following:
char ipv6Addr[INET6_ADDRSTRLEN + 1];
char ipv6Mask[INET6_ADDRSTRLEN + 1];

  inet_ntop(AF_INET6, &match->dstIp6, ipv6Addr, sizeof(addrBuf));
  inet_ntop(AF_INET6, &match->dstIp6Mask, ipv6Mask, sizeof(addrMaskBuf));
  printf(" dstIp6 = %s/%s", ipv6Addr, ipv6Mask);

**Comment by capveg** [comment]
Thanks for digging into this @bhavishkhatri  : any chance for a quick patch?

**Comment by capveg** [comment]
For completeness: @bhavishkhatri  posted https://github.com/opennetworklinux/ofdpa-2.0/pull/1 which has been merged.  Still need to verify the fix, update the git submodule pointer to the newer ofdpa-2.0 tree, bump the .deb version number, and produce a new .deb package.  I'll leave this ticket open until those things are processed.
