### ISSUE TITLE
TODO: Orc has CLI bug - can segfault

### ISSUE THREAD

**Issue by capveg** [opennetworklinux/ONL#143]
Possible problem: fwd_loop.c:95 does not allocate an FD entry for CLI.  Need to +1 if CLI is in use

Trivial to fix: just need to code and test.

**Comment by rizard** [comment]
@capveg How does this look?
https://github.com/floodlight/bigcode/pull/58/files#diff-bfe41bcbb830c64f7c30d19f17b61604R95

**Comment by capveg** [comment]
The change looks correct (thanks!) but the patch is a bit of a mess: lots
of stray whitespace changes.  Were they intentional?  I don't think the
whitespace changes are necessary so it would be great to get the patch
reformatted without them.  Also, because this is a different change from
your OF-DPA driver changes, probably better to have in a different branch
and pull request.

Thanks for jumping on this.

**Comment by rizard** [comment]
@capveg Sure, I noticed the whitespace diff too. I did not intentionally change them, but git certainly thinks I did. I'll look into it along with a separate pull request.

**Comment by capveg** [comment]
FYI, it's considered a good practice to setup your editor to replace tabs
with spaces.  Let me know what editor you're using and I can point you at
the relevant editor config settings.

- Rob
.

**Comment by rizard** [comment]
@capveg Hmm, I have done that already in my vimrc and also in Xcode.

I think I see what's happened -- Xcode appears to have inserted spaces automatically with autoindent. It looks like it "repaired" the entire file and added the spaces on the blank lines too. I'll stick with vim I suppose when redoing the pull request.

**Comment by capveg** [comment]
Fixed in https://github.com/floodlight/bigcode/pull/61
