### ISSUE TITLE
use linux kernel 2.6 with ONL

### ISSUE THREAD

**Issue by vic1231** [opennetworklinux/ONL#170]
Is it possible?
I have the brcm sdk, and built it with linux kernel 2.6. I tried to build that sdk with ONL, the kernel 3.x, but fails.
So I thought if ONL can support kernel 2.6 as a build option?

**Comment by sonoble** [comment]
Hi Vic,

We supply the Broadcom kernel modules for the 3.2 kernel in our installer.  Are you using a newer version of the SDK or attempting to use OpenNSL?

**Comment by vic1231** [comment]
I knew OpenNSL. 
1. You mean OpenNSL was included in ONL?  
2. I knew the ONL support the brcm SDK(OpenNSL?), but do not know how to start it yet. Does it use bcm.user to start up?  
3. How to put my switch configs in ONL?
4. Actually, I need the newest brcm SDK, the version 6.4.8, or later.

**Comment by sonoble** [comment]
Hi Vic,

1. If you pull the wedge branch, it has OpenNSL modules and is able to use the library directly from the Broadcom github.
2. When you run "orc" on a supported platform, it will install the kernel modules and start up the SDK
3. You can look at how others have done it such as Quanta : https://github.com/opennetworklinux/onlp-quanta
4. What kernel are you using currently? We don't support the latest SDK but will as we start to upgrade parts including the kernel.

**Comment by vic1231** [comment]
Hi sonoble:
Thanks for your advise, I will refer that.
Now I also use ONL default kernel(3.2) now.
