### ISSUE TITLE
EdgeCore 4610-54 (arm-accton-as4610-54-r0) support

### ISSUE THREAD

**Issue by ongrid** [opennetworklinux/ONL#176]
Hi folks!
Do we have any plans for support arm-accton-as4610-54-r0 (EdgeCore 4610-54)
For now installer version 603b111 (powerpc.all,2015.12.02.20.40,603b11102a1c6e5174a68132422ab53503f6b080) exits  with "This installer does not support the arm-accton-as4610-54-r0 platform." message.

**Comment by sonoble** [comment]
Hi!

We would need someone to submit arm support for ONL.  Our plan is to support ARM once we have the necessary generic support.

**Comment by kvarlamo** [comment]
Hi Steven!
Thanks for your reply!
Sorry for stupid question - I'm unaware of your processes. Do I understand correctly that we are waiting until some ARM boxes vendor offer its efforts to promote this? Who can trigger these activities to start supporting particular switch? Hardware vendor? Application vendor? NP vendor?

**Comment by GrantMackey-WDC** [comment]
I'm in a similar situation, I didn't realize there wasn't arm support in ONL when I purchased this switch. Is this mostly a cross compile and test situation? or is it more difficult than that?

Willing to be a guinea pig for this, as I'm not too keen on buying a license for a NOS yet.

**Comment by sonoble** [comment]
Hi Grant,

I've been talking to NXP/Freescale about ARM.  I believe we will need a more current kernel than even the 3.18 that we are putting in now, possibly a 4.x kernel to support the newer ARM architectures.  What switch did you purchase?

**Comment by GrantMackey-WDC** [comment]
I purchased the switch you've referenced, the arm-accton-as4610-54-r0

I see, how have your discussions gone? I've been trying to get the picaOS 3mo trial onto this switch and even that is not going well >.< It says that it is ONIE compatible, but halfway through the install it goes sideways and fails (during device partitioning) and I've yet to get workable feedback from edgecore or pica. /rant so I was hoping this would be relatively straight-forward.

**Comment by kvarlamo** [comment]
Hi, I had a lot of issues with partitioning during installation.
Erasing all partitions via ONIE fdisk before ONL installation always helped me.
fdisk /dev/sdX (exact device id can be found from dmesg output)
p
d
d
d
p
w

CAUTION: This trick seems to be secure with ppc switches which contain hard-coded ONIE, but don't use this trick with x86 switches which may run ONIE from the same disk as ONL.

**Comment by GrantMackey-WDC** [comment]
@kvarlamo Have you tried this with an arm based one yet?

**Comment by kvarlamo** [comment]
Never, but I believe OS partitions removal should be secure and not impact ONIE-containing memory (which located on EEPROM/NVRAM on non x86 architectures).

**Comment by GrantMackey-WDC** [comment]
Gotcha, okay that is good to know. I did want to follow up on this one. After talking to the folks at both edge-core and pica, there was an issue with their last release that they're rectifying in their next release. 

Thanks for the help.
