### ISSUE TITLE
[imt] install error under new ONIE master-201601281358.

### ISSUE THREAD

**Issue by vitalivanov** [opennetworklinux/ONL#195]
Interface Masters platforms added to OCP/ONIE.

When to build latest ONIE from sources then there is a problem for ONL installations:

```
ONIE:/ # onie-sysinfo -a
Unknown Unknown 00:13:95:12:9a:68 master-201601281358 30324 im_n29xx_t40n 0 x86_64-im_n29xx_t40n-r0 x86_64 1 msdos 2016-01-28T14:30+0200
```

Install error:

```
ONIE:/ # onie-nos-install http://192.168.157.98/onl/onl-18cc760-amd64-all.2016.0
1.04.21.36.installer
...
found a disk with 62533296 blocks                                         
next usable block is at 264192
Creating 32GiB for ONL boot
 tune2fs: Bad magic number in super-block while trying to open /dev/sda
Couldn't find valid filesystem superblock.
tune2fs 1.42.8 (20-Jun-2013)
Install failed.
```

**Comment by sonoble** [comment]
Hi Vitaliy,

As we have moved to the new design, it is probably better to spend time
updating the install script on that than working on the depreciated onl.

opencomputeproject/OpenNetworkLinux/blob/master/builds/amd64/installer/legacy/builds/amd64-installer.sh

See if you can integrate the msdos  modifications you made into that
script.

**Comment by vitalivanov** [comment]
Steven, until we moved to OCP/ONL pushing the change here, just not to loose it.

Our IMT/ONL includes this change...
