### ISSUE TITLE
Build issue in make onl-x86

### ISSUE THREAD

**Issue by suriya92** [opennetworklinux/ONL#199]
Hi
I am trying to build ONL using the instructions on the webpage on my Ubuntu 14.043 LTS (to get the installer for x86).but i get this error after "make onl-x86",

root@onl-builder:/home/suriya/ONL# sudo make onl-x86
export ONL=`pwd` && make -C $ONL/builds/components
make[1]: Entering directory `/home/suriya/ONL/builds/components'
WARNING:onlpkg:no matching packages for faultd-dbg (amd64)
INFO:onlpkg:can be built locally at /home/suriya/ONL/components/amd64/faultd
make[2]: Entering directory`/home/suriya/ONL/components/amd64/faultd'
rm -rf /home/suriya/ONL/components/any/faultd/deb/debuild-amd64
cp -R /home/suriya/ONL/components/any/faultd/deb/debuild /home/suriya/ONL/components/any/faultd/deb/debuild-amd64
make -C /home/suriya/ONL/components/any/faultd deb DEBUILD_DIR=debuild-amd64
make[3]: Entering directory `/home/suriya/ONL/components/any/faultd'
make -C deb
make[7]: warning: -jN forced in submake: disabling jobserver mode.
make[7]: *** No rule to make target`/usr/include/stdc-predef.h', needed by `/home/suriya/ONL/components/amd64/faultd/build/x86_64-linux-gnu/obj//home/suriya/ONL/submodules/common/modules/faultd//module/src//faultd.o'.  Stop.
make[6]: *** [component] Error 2
make[5]: *** [deb] Error 2
make[4]: *** [deb] Error 2
make[3]: *** [deb] Error 2
make[3]: Leaving directory`/home/suriya/ONL/components/any/faultd'
make[2]: **\* [deb] Error 2
make[2]: Leaving directory `/home/suriya/ONL/components/amd64/faultd'
Traceback (most recent call last):
  File "/home/suriya/ONL/tools/onlpkg.py", line 301, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/suriya/ONL/tools/onlpkg.py", line 167, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/suriya/ONL/components/amd64/faultd', 'deb')' returned non-zero exit status 2
make[1]: *** [component-deps] Error 1
make[1]: Leaving directory`/home/suriya/ONL/builds/components'
make: **\* [all-components] Error 2

Please help me with you ideas.

**Comment by sonoble** [comment]
Hi Suriya,

Is there a reason you are not using the OCP release of ONL? https://github.com/opencomputeproject/OpenNetworkLinux 

I can try and help you with the older ONL, but it is depreciated at this point.

**Comment by suriya92** [comment]
Hi sonable,

The OCP release of ONL has the steps to build a Debian 7 based ONL. But I need an installer that would work on Ubuntu or any other Linux distribution.And do we have command for x-86 there?

**Comment by sonoble** [comment]
Hi Suriya,

We use Debian 7/8 as our OS for ONL.. there is no option to build a non Debian based ONL.  Everything you are doing within the docker image is in Debian.  The same build options that you have for this ONL exist in the OCP one, there is a "make docker" command that will build everything for you.

**Comment by suriya92** [comment]
Thanks for the information Steven. But is there a way to build specifically for x-86? I'm a newbie to ONL. Your help is greatly appreciated.

**Comment by sonoble** [comment]
yes, you can do "make onl-x86" once you have started onlbuilder which is what you have done above.

I would try deleting the ONL build, re cloning, running make docker and then make onl-x86.  I would also suggest running this under a non-root account.

btw if it was not clear earlier, you can build on Ubuntu or any linux you want, but ONL itself builds in a debian docker image and will be based on debian.

**Comment by suriya92** [comment]
I tried by deleting the build, re cloning and running make docker. But it throws errors at that spot.

suriya@CAKproj-machine2:~/OpenNetworkLinux$ sudo make docker
Pulling opennetworklinux/builder7:1.1...
done.
[ ok ] Starting apt-cacher-ng: apt-cacher-ng.
[ ok ] Enabling additional executable binary formats: binfmt-support.
Submodule 'sm/infra' (git://github.com/floodlight/infra) registered for path 'sm/infra'
Cloning into 'sm/infra'...
fatal: unable to connect to github.com:
github.com: Name or service not known

Clone of 'git://github.com/floodlight/infra' into submodule path 'sm/infra' failed
ERROR:submodules:git error updating module sm/infra
Submodule 'sm/bigcode' (git://github.com/floodlight/bigcode) registered for path 'sm/bigcode'
Cloning into 'sm/bigcode'...
fatal: unable to connect to github.com:
github.com: Name or service not known

Clone of 'git://github.com/floodlight/bigcode' into submodule path 'sm/bigcode' failed
ERROR:submodules:git error updating module sm/bigcode
make: /home/suriya/OpenNetworkLinux/sm/infra/builder/unix/tools/mmg.py: Command not found
make -C packages/base/amd64/kernels
make[1]: /home/suriya/OpenNetworkLinux/sm/infra/builder/unix/tools/mmg.py: Command not found
make[1]: Entering directory `/home/suriya/OpenNetworkLinux/packages/base/amd64/kernels'
make[2]: /home/suriya/OpenNetworkLinux/sm/infra/builder/unix/tools/mmg.py: Command not found
make[2]: Entering directory `/home/suriya/OpenNetworkLinux/packages/base/amd64/kernels/kernel-3.18-x68-64-all/builds'
make -C /home/suriya/OpenNetworkLinux/packages/base/any/kernels/3.18.25/configs/x86_64-all K_TARGET_DIR=/home/suriya/OpenNetworkLinux/packages/base/amd64/kernels/kernel-3.18-x68-64-all/builds -j16
make[3]: /home/suriya/OpenNetworkLinux/sm/infra/builder/unix/tools/mmg.py: Command not found
make[3]: Entering directory `/home/suriya/OpenNetworkLinux/packages/base/any/kernels/3.18.25/configs/x86_64-all'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
cd /home/suriya/OpenNetworkLinux/packages/base/any/kernels/archives && wget http://opennetlinux.org/tarballs/linux-3.18.25.tar.xz
--2016-02-18 15:15:51--  http://opennetlinux.org/tarballs/linux-3.18.25.tar.xz
Resolving opennetlinux.org (opennetlinux.org)... failed: Name or service not known.
wget: unable to resolve host address `opennetlinux.org'
make[3]: *** [/home/suriya/OpenNetworkLinux/packages/base/any/kernels/archives/linux-3.18.25.tar.xz] Error 4
make[3]: Leaving directory `/home/suriya/OpenNetworkLinux/packages/base/any/kernels/3.18.25/configs/x86_64-all'
make[2]: *** [kernel] Error 2
make[2]: Leaving directory `/home/suriya/OpenNetworkLinux/packages/base/amd64/kernels/kernel-3.18-x68-64-all/builds'
ERROR:onlpm:'Build failed.'
make[1]: *** [pkgall] Error 1
make[1]: Leaving directory `/home/suriya/OpenNetworkLinux/packages/base/amd64/kernels'
make: *** [amd64] Error 2
make: *** [docker] Error 2
suriya@CAKproj-machine2:~/OpenNetworkLinux$

**Comment by suriya92** [comment]
And do you have any precompiled binaries for x-86?

**Comment by sonoble** [comment]
Yes, we do, you can find them here http://opennetlinux.org/binaries  where http://opennetlinux.org/binaries/latest-amd64.installer would be the latest ONL 1.0 (the one you are trying to build) amd64 build.

**Comment by suriya92** [comment]
Thanks. But also please let me know your ideas on my error because it would be better if I can build on my own.

**Comment by sonoble** [comment]
Hi,

failed: Name or service not known. wget: unable to resolve host address opennetlinux.org

This tells me that DNS is not working on your machine.  Can you confirm that the docker host is able to do DNS lookups?  You should be able to resolve opennetlinux.org, if not, then nothing will work.

**Comment by suriya92** [comment]
Hi Steven,

I resolved the DNS issue and tried to build by hand using the command "make amd64" and this is what I get :

Fetched 31.2 kB in 0s (34.6 kB/s)
Reading package lists... Done
W: Failed to fetch http://127.0.0.1:3142/mirrors.kernel.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://127.0.0.1:3142/mirrors.kernel.org/debian/dists/jessie/Release.gpg  Unable to connect to 127.0.0.1:3142:

W: Some index files failed to download. They have been ignored, or old ones used instead.
I: Calculating required packages.
apt-get -y  -o Apt::Architecture=amd64 -o Dir::Etc::TrustedParts=/home/monica/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/etc/apt/trusted.gpg.d -o Dir::Etc::Trusted=/home/monica/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/etc/apt/trusted.gpg.d/trusted.gpg -o Apt::Get::AllowUnauthenticated=true -o Apt::Get::Download-Only=true -o Apt::Install-Recommends=false -o Dir=/home/monica/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/ -o Dir::Etc=/home/monica/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/etc/apt/ -o Dir::Etc::Parts=/home/monica/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/etc/apt/apt.conf.d/ -o Dir::Etc::PreferencesParts=/home/monica/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/etc/apt/preferences.d/ -o APT::Default-Release=* -o Dir::State=/home/monica/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/var/lib/apt/ -o Dir::State::Status=/home/monica/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/var/lib/dpkg/status -o Dir::Cache=/home/monica/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/var/cache/apt/ install  apt apt-utils base-files binutils bsdmainutils cpio debian-archive-keyring dmidecode dosfstools ethtool fancontrol file grub2 i2c-tools ifupdown iproute iptables iputils-ping isc-dhcp-client kexec-tools less lm-sensors localepurge locales lsof make mingetty module-init-tools mtd-utils nano net-tools netbase netplug nfs-common ntp ntpdate onl-faultd onl-loader-initscripts onl-platform-config-x86-64-accton-as5712-54x-r0 onl-platform-config-x86-64-accton-as5812-54t-r0 onl-platform-config-x86-64-accton-as5812-54x-r0 onl-platform-config-x86-64-accton-as6712-32x-r0 onl-platform-config-x86-64-accton-as6812-32x-r0 onl-platform-config-x86-64-accton-as7512-32x-r0 onl-platform-config-x86-64-accton-as7712-32x-r0 onl-platform-config-x86-64-accton-wedge-16x-r0 onl-platform-config-x86-64-cel-redstone-xp-r0 onl-platform-config-x86-64-quanta-ly6-rangeley-r0 onl-platform-config-x86-64-quanta-ly8-rangeley-r0 onlp onlp-snmpd onlp-x86-64-accton-as5712-54x-r0 onlp-x86-64-accton-as5812-54t-r0 onlp-x86-64-accton-as5812-54x-r0 onlp-x86-64-accton-as6712-32x-r0 onlp-x86-64-accton-as6812-32x-r0 onlp-x86-64-accton-as7512-32x-r0 onlp-x86-64-accton-as7712-32x-r0 onlp-x86-64-accton-wedge-16x-r0 onlp-x86-64-cel-redstone-xp-r0 onlp-x86-64-quanta-ly6-rangeley-r0 onlp-x86-64-quanta-ly8-rangeley-r0 openssh-server parted pciutils procps psmisc python python-cherrypy3 python-pyinotify python-pypcap python-tz realpath resolvconf rssh rsyslog scapy smartmontools snmpd sudo sysvinit-core telnetd traceroute u-boot-tools usbutils util-linux vim-tiny watchdog wget zile
Reading package lists... Done
Building dependency tree... Done
Package binutils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package iptables is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package apt
E: Unable to locate package apt-utils
E: Unable to locate package base-files
E: Package 'binutils' has no installation candidate
E: Unable to locate package bsdmainutils
E: Unable to locate package cpio
E: Unable to locate package debian-archive-keyring
E: Unable to locate package dmidecode
E: Unable to locate package dosfstools
E: Unable to locate package ethtool
E: Unable to locate package fancontrol
E: Unable to locate package file
E: Unable to locate package grub2
E: Unable to locate package i2c-tools
E: Unable to locate package ifupdown
E: Unable to locate package iproute
E: Package 'iptables' has no installation candidate
E: Unable to locate package iputils-ping
E: Unable to locate package isc-dhcp-client
E: Unable to locate package kexec-tools
E: Unable to locate package less
E: Unable to locate package lm-sensors
E: Unable to locate package localepurge
E: Unable to locate package locales
E: Unable to locate package lsof
E: Unable to locate package make
E: Unable to locate package mingetty
E: Unable to locate package module-init-tools
E: Unable to locate package mtd-utils
E: Unable to locate package nano
E: Unable to locate package net-tools
E: Unable to locate package netbase
E: Unable to locate package netplug
E: Unable to locate package nfs-common
E: Unable to locate package ntp
E: Unable to locate package ntpdate
E: Unable to locate package openssh-server
E: Unable to locate package parted
E: Unable to locate package pciutils
E: Unable to locate package procps
E: Unable to locate package psmisc
E: Package 'python' has no installation candidate
E: Unable to locate package python-cherrypy3
E: Unable to locate package python-pyinotify
E: Unable to locate package python-pypcap
E: Unable to locate package python-tz
E: Unable to locate package realpath
E: Unable to locate package resolvconf
E: Unable to locate package rssh
E: Unable to locate package rsyslog
E: Unable to locate package scapy
E: Unable to locate package smartmontools
E: Unable to locate package snmpd
E: Unable to locate package sudo
E: Unable to locate package sysvinit-core
E: Unable to locate package telnetd
E: Unable to locate package traceroute
E: Unable to locate package u-boot-tools
E: Unable to locate package usbutils
E: Unable to locate package util-linux
E: Unable to locate package vim-tiny
E: Unable to locate package watchdog
E: Unable to locate package wget
E: Unable to locate package zile
apt download failed. Exit value: 100
ERROR:onlrfs:Multistrap APT failure.
/home/monica/OpenNetworkLinux/make/rfs.mk:32: recipe for target 'RFS' failed
make[2]: *** [RFS] Error 1
make[2]: Leaving directory '/home/monica/OpenNetworkLinux/builds/amd64/rootfs/builds'
ERROR:onlpm:'Build failed.'
/home/monica/OpenNetworkLinux/make/pkg.mk:21: recipe for target 'pkgall' failed
make[1]: *** [pkgall] Error 1
make[1]: Leaving directory '/home/monica/OpenNetworkLinux/builds/amd64/rootfs'
Makefile:19: recipe for target 'amd64' failed
make: *** [amd64] Error 2

Pls throw some light on this !

**Comment by sonoble** [comment]
Hello,

Please run apt-cacher-ng first, then run the make command.

**Comment by suriya92** [comment]
It worked. Thank you so much for all the help !

**Comment by sm1988** [comment]
Hi Steven / Suriya ,

I am trying to build an x86-64 image for my Dell S6000-on OCP switch which has ONIE installed on it. I am using build instructions from http://opennetlinux.org/docs/build. But there is something wrong, please suggest! Or if there is one pre-built image please share the link.

Dev Host Details:
Linux  4.4.0-64-generic #85-Ubuntu SMP x86_64 GNU/Linux
=================
root@dell-dev-host:/mnt/OpenNetworkLinux# make onl-x86
make -C packages/base/all
make[1]: Entering directory '/mnt/OpenNetworkLinux/packages/base/all'
GEN pkgall
1.5.9
ERROR:onlpm:'No debian package.'
/mnt/OpenNetworkLinux/make/pkg.mk:30: recipe for target 'pkgall' failed
make[1]: *** [pkgall] Error 1
make[1]: Leaving directory '/mnt/OpenNetworkLinux/packages/base/all'
Makefile:73: recipe for target 'packages_base_all' failed
make: *** [packages_base_all] Error 2
==================================

Appreciate the help!

Thanks,
Shishir

**Comment by sonoble** [comment]
Hello, you will want to grab an image from the website as the Dell platforms are not build-able outside of our internal network due to NDA issues.
http://opennetlinux.org/binaries/latest-DEB8-AMD64-swi.installer is the latest Debian 8 based installer.
