### ISSUE TITLE
cp: target `buildroot/package/busybox/' is not a directory

### ISSUE THREAD

**Issue by vitalivanov** [opennetworklinux/ONL#20]
Host OS:

$ uname -a
Linux vitaliy-Inspiron-7520 3.2.0-64-generic #97-Ubuntu SMP Wed Jun 4 22:04:21 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="12.04.4 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.4 LTS)"
VERSION_ID="12.04"

When performing steps from docs at:
http://opennetlinux.org/docs/build

#> export ONL=`pwd`
#> cd $ONL/builds/components
#> make
...
make[1]: Leaving directory `/home/vitaliy/VITALIY/IMT/OCP/ONL/ONL/components/all/platform-config/qemu/deb/debuild'
   dh_install
   dh_installdocs
   dh_installchangelogs
   dh_installexamples
   dh_installman
   dh_installcatalogs
   dh_installcron
   dh_installdebconf
   dh_installemacsen
   dh_installifupdown
   dh_installinfo
   dh_installinit
   dh_installmenu
   dh_installmime
   dh_installmodules
   dh_installlogcheck
   dh_installlogrotate
   dh_installpam
   dh_installppp
   dh_installudev
   dh_installwm
   dh_installxfonts
   dh_installgsettings
   dh_bugfiles
   dh_ucf
   dh_lintian
   dh_gconf
   dh_icons
   dh_perl
   dh_usrlocal
   dh_link
   dh_compress
   dh_fixperms
   dh_installdeb
   dh_gencontrol
   dh_md5sums
   dh_builddeb
dpkg-deb: building package `platform-config-qemu' in `../platform-config-qemu_0.1.0bsn1~ubuntu1_all.deb'.
 dpkg-genchanges -b >../platform-config-qemu_0.1.0bsn1~ubuntu1_amd64.changes
dpkg-genchanges: binary-only upload - not including any source code
 dpkg-source --after-build debuild
dpkg-buildpackage: binary only upload (no source included)
Now running lintian...
E: platform-config-qemu: description-synopsis-is-duplicated
W: platform-config-qemu: script-not-executable lib/platform-config/qemu/python/onlpc.py
Finished running lintian.
/home/vitaliy/VITALIY/IMT/OCP/ONL/ONL/tools/onlpkg.py --add-pkg *all*.deb
INFO:onlpkg:adding new package platform-config-qemu_0.1.0bsn1~ubuntu1_all.deb...
rm *all*.deb
rm -rf debuild/debian/tmp debuild/debian/platform-config-qemu/ debuild/debian/platform-config-qemu-dbg
cp patches/busybox-001-init-quiet-restart.patch patches/busybox-002-checkpass-command.patch buildroot/package/busybox/
cp: target `buildroot/package/busybox/' is not a directory
make[7]: *** [setup] Error 1
make[6]: *** [/home/vitaliy/VITALIY/IMT/OCP/ONL/ONL/submodules/loader/.setup.done] Error 2
make[5]: *** [component] Error 2
make[4]: *** [deb] Error 2
make[3]: *** [deb] Error 2
make[2]: *** [deb] Error 2
make[2]: Leaving directory `/home/vitaliy/VITALIY/IMT/OCP/ONL/ONL/components/i386/initrd-i386'
Traceback (most recent call last):
  File "/home/vitaliy/VITALIY/IMT/OCP/ONL/ONL/tools/onlpkg.py", line 257, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/vitaliy/VITALIY/IMT/OCP/ONL/ONL/tools/onlpkg.py", line 127, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/vitaliy/VITALIY/IMT/OCP/ONL/ONL/components/i386/initrd-i386', 'deb')' returned non-zero exit status 2
make[1]: *** [component-deps] Error 1
make[1]: Leaving directory `/home/vitaliy/VITALIY/IMT/OCP/ONL/ONL/components/i386/loader-i386'
Traceback (most recent call last):
  File "/home/vitaliy/VITALIY/IMT/OCP/ONL/ONL/tools/onlpkg.py", line 257, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/vitaliy/VITALIY/IMT/OCP/ONL/ONL/tools/onlpkg.py", line 127, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/vitaliy/VITALIY/IMT/OCP/ONL/ONL/components/i386/loader-i386', 'deb')' returned non-zero exit status 2
make: *** [component-deps] Error 1

Please advice.

**Comment by larryming** [comment]
Is this issue fixed? I meet this issue but I can't find the solution.

**Comment by capveg** [comment]
Hi Larry,

It's an intermittent issue that happens when one of the dynamic downloads
fails during the build process.  Vitaly's work around should still work for
you.  Have you tried:

Quick workaround would be to go to:
1. cd $ONL/submodules/loader
2. git submodule init
3. git submodule update

- Rob
.

**Comment by larryming** [comment]
Hi Rob,

Thank very much for your quick response!
I have done as your steps but still failed:
(iso1:ws.amd64)larry@larry-VirtualBox:~/work/ONL/submodules/loader$ git submodule update
error: Problem with the SSL CA cert (path? access rights?) while accessing https://git.buildroot.net/buildroot/info/refs
fatal: HTTP request failed
Unable to fetch in submodule path 'buildroot'
(iso1:ws.amd64)larry@larry-VirtualBox:~/work/ONL/submodules/loader$ git config --global url."https://".insteadOf git://
(iso1:ws.amd64)larry@larry-VirtualBox:~/work/ONL/submodules/loader$ rm -rf buildroot
(iso1:ws.amd64)larry@larry-VirtualBox:~/work/ONL/submodules/loader$ git submodule init
Submodule 'buildroot' () registered for path 'buildroot'
(iso1:ws.amd64)larry@larry-VirtualBox:~/work/ONL/submodules/loader$ git submodule update
error: Problem with the SSL CA cert (path? access rights?) while accessing https://git.buildroot.net/buildroot/info/refs
fatal: HTTP request failed
Unable to fetch in submodule path 'buildroot'
(iso1:ws.amd64)larry@larry-VirtualBox:~/work/ONL/submodules/loader$ 

Regards,
Larry Ming

**Comment by capveg** [comment]
Hi Larry,

It seems to be an issue with the remote server.  My guess is that it will
resolve once they fix it.

At least from our side, then intent (though longer term) is to replace the
buildroot part of the loader.

Are you intent on building the loader from source or have you seen the
pre-compiled binaries available from http://opennetlinux.org/binaries ?

- Rob
.

**Comment by larryming** [comment]
I want to build ONL from source.

The new problem:
(iso1:ws.amd64)larry@larry-VirtualBox:~/work/ONL/submodules/loader$ git submodule update
error: gnutls_handshake() failed: A TLS warning alert has been received. while accessing https://git.buildroot.net/buildroot/info/refs
fatal: HTTP request failed
Unable to fetch in submodule path 'buildroot'

Regards,
Larry Ming

**Comment by capveg** [comment]
So, I was able to blow away my install and check it out just now without
problem.

A couple of potential issues:

1) I'm using the git:// style URL which is the default instead of https.
Your problem seems to be because you're using https -- why are you doing
that?

2) TLS warning alerts can be issued for lots of things including your local
time being out of date or the remote certificate being signed.  Trying to
dig into what the more specific error is can help point you in the right
direction.

- Rob
.

**Comment by larryming** [comment]
Hi Rob,

I use "git clone http://git.buildroot.net/buildroot" to fix the TLS issue.

Thanks!
Larry Ming

**Comment by capveg** [comment]
I believe this should be fixed with the new build system.  I uncovered some race conditions in the old build system that made this more likely.  If folks see this again, please reopen this ticket so we can track it.
