### ISSUE TITLE
I can't see any kernel modules after "apt-get install vlan" 

### ISSUE THREAD

**Issue by GitHubPascal** [opennetworklinux/ONL#200]
I try to install the vlan modules to the ONL.
1. "sudo apt-get update".
2. "sudo apt-get install vlan".
3. "lsmod" is empty. I can't find any kernel modules.

BTW:
Follow this link :http://www.microhowto.info/howto/configure_an_ethernet_interface_as_a_vlan_trunk_on_debian.html . 
I try to run the command "sudo apt-get install  linux-image-3.16.0-4-amd64", also failed.

How can install the vlan modules to the ONL?
Thanks.

**Comment by GitHubPascal** [comment]
Use the latest ONL code, build the image with the x86 platform.
And try the cumulus image, it works well.

**Comment by capveg** [comment]
Hi,

The workflow and toolset you're talking about does not work out of the box on ONL.  If you want VLAN functionality, you need to use one of the many open source tools that ONL does support like ORC or FBOSS.  The lower level APIs (e.g., via OpenNSL) are exposed in ONL, so if you want this command to work like it does on Cumulus, it's not too much work for you to implement it yourself.

I'm going to close out this issue as working as intended.  If you want to work on this feature, feel free to open another issue so we can track this as a feature request.

Thanks for the interest.

**Comment by GitHubPascal** [comment]
Hi Capveg:

Thanks for your reply. 
In fact I only want to insmod one kernel module and can see it with "lsmod". 
"apt-get install vlan" is only the example. 
This is the basic function for all the Linux. 
At now, I can't sure the insmod function works well or not on the ONL.

**Comment by sonoble** [comment]
Hi Pascal,

I would look at https://github.com/opencomputeproject/OpenNetworkLinux where we have migrated ONL to.  It has a newer kernel available (3.18) and you are always free to recompile the kernel with modules that you want by patching/modifying the configuration.

https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/packages/base/any/kernels/3.18.25/configs/x86_64-all/x86_64-all.config

**Comment by GitHubPascal** [comment]
Hi Sonoble:

Thanks for your help. I will try to build your kernel and run on my Celestica Redstone-XP switch.
Thank very much.

**Comment by GitHubPascal** [comment]
Hi Sonoble:

Thanks for your reply.
i will change my work path. Porting the broadcom SDK first, and then try to porting the ISS. 
Hope it works
