### ISSUE TITLE
The ONL kernel version of the built image and run-time image is inconsistent

### ISSUE THREAD

**Issue by royeshao** [opennetworklinux/ONL#201]
Hi there,

We try port ONL on our platform(Intel Rangeley 32xPort) by ONIE recently. 

First, we successfully compile(build) the source image by Debian8.4 OS, and we export VERSION=8 to environment. 

Second, we configure our ONIE config file (/etc/machine.conf) to setup onie_platform & onie_machine to be accton_as7712_32x. 
(Assume our platform is it or ONIE will return error)

Then ONIE will bring up ONL succeed and we can login ONL shell environment. 
But when we execute 'uname -a' for check our kernel version, it shows "Linux (none) 3.2.65-1+deb7u2-OpenNetworkLinux". 

We think it's inconsistent with our built image. 
We actually export VERSION=8 and compile succeed.

By the way, we try to download the binary image (latest-DEB8-AMD64-installed.installer),
It has the same result (Kernel version is inconsistent).
 
Is there any procedure which we miss?
Or any hint could be helpful for us.

Thank you very much
With best regards

Roye

**Comment by sonoble** [comment]
Hi Roye are you using this repo or the OCP one? https://github.com/opencomputeproject/OpenNetworkLinux is where ONL lives now.

Can you cat the /etc/debian_version ?

**Comment by royeshao** [comment]
Hi Sonable,

Yes, we git download the ONL from your address link.
and below is the message by cat /etc/debian_version
------------------------------------------------
roye@roye:~$ sudo cat /etc/debian_version
8.4
------------------------------------------------
Is it right information for you?

By thew way, we build succeed of this ONL image
Below is the repository list
------------------------------------------------------------------------------------------------
roye@roye:~/OpenNetworkLinux$ ls -al builds/amd64/installer/installed/builds/
total 175548
drwxr-xr-x 3 roye roye      4096 Sep 14 02:27 .
drwxr-xr-x 3 roye roye      4096 Sep 13 18:51 ..
-rw-r--r-- 1 roye roye        62 Sep 13 04:56 boot-config
drwxr-xr-x 2 roye roye      4096 Sep 13 04:56 config
-rw-r--r-- 1 roye roye        11 Sep 13 04:56 .gitignore
-rw-r--r-- 1 roye roye       112 Sep 13 04:56 Makefile
-rwxr-xr-x 1 root root    179729242 Sep 14 02:27 ONL-2.0.0_ONL-OS_2016-09-13.0950-2d3475b_AMD64_INSTALLED_INSTALLER
-rw-r--r-- 1 root root           33 Sep 14 02:27 ONL-2.0.0_ONL-OS_2016-09-13.0950-2d3475b_AMD64_INSTALLED_INSTALLER.md5sum
roye@roye:~/OpenNetworkLinux$
------------------------------------------------------------------------------------------------

Thanks your response :)

**Comment by sonoble** [comment]
Hi Roye, 

I am still unsure of the problem, the system seems to boot, does the network (ifconfig ma1) work?

**Comment by royeshao** [comment]
Hi Steven,

Above log is paste from my build server not from ONL OS.

Yes, it's looks like works.
Below is the log of ONL OS

loader#
loader# uname -r
3.2.65-1+deb7u2-OpenNetworkLinux
loader#
loader# ifconfig
ma1       Link encap:Ethernet  HWaddr 00:05:64:2F:3C:58
          inet6 addr: fe80::205:64ff:fe2f:3c58/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:384 errors:0 dropped:2 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:40893 (39.9 KiB)  TX bytes:468 (468.0 B)
          Memory:dfe60000-dfe80000
loader#
loader# igb: ma1 NIC Link is Down
igb: ma1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
loader#
loader# ifconfig
ma1       Link encap:Ethernet  HWaddr 00:05:64:2F:3C:58
          inet6 addr: fe80::205:64ff:fe2f:3c58/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:395 errors:0 dropped:2 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:42084 (41.0 KiB)  TX bytes:468 (468.0 B)
          Memory:dfe60000-dfe80000

Our issue is that why our boot-up ONL's kernel  is 3.2.65-1+deb7u2-OpenNetworkLinux(Debian 7)?
We expect it will be debian8.

Is there any suggestion for try or check the procedures?

Thanks for your response :)

**Comment by sonoble** [comment]
Deb7 refers to the maintenance release of the kernel, it is maintained by wheezy (debian 7) and has the debian 7 patches. It is compiled and running on Debian 8. We also have a 3.16 kernel if you want something newer (the long term support kernel from Debian 8).

**Comment by royeshao** [comment]
Hi Steven,
I see.
And we have another issue is that how to assign the kernel version for build ONL?
We find the kernel source in /OpenNetworkLinux/packages/base/any/kernels.
roye@roye:~/OpenNetworkLinux/packages/base/any/kernels$ ll
total 32
drwxr-xr-x  8 roye roye 4096 Sep 13 04:56 .
drwxr-xr-x 10 roye roye 4096 Sep 13 04:56 ..
drwxr-xr-x  4 roye roye 4096 Sep 13 04:56 3.16+deb8
drwxr-xr-x  4 roye roye 4096 Sep 13 04:56 3.18.25
drwxr-xr-x  4 roye roye 4096 Sep 13 04:56 3.2.65-1+deb7u2
drwxr-xr-x  4 roye roye 4096 Sep 13 04:56 3.2.71-1+deb7
drwxr-xr-x  2 roye roye 4096 Sep 13 23:13 archives
drwxr-xr-x  4 roye roye 4096 Sep 13 04:56 legacy

Where or how can we assign build procedure by kernel 3.16+deb8?

Thanks

**Comment by sonoble** [comment]
Hi, you can define the kernel under the lib directory for your system, here is an example of the as5512 using the 3.18 kernel,  you would just put 3-16 https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/packages/platforms/accton/x86-64/x86-64-accton-as5512-54x/platform-config/r0/src/lib/x86-64-accton-as5512-54x-r0.yml

**Comment by royeshao** [comment]
Hi Steven,
Thanks, we will re-try it.
Regards

**Comment by sonoble** [comment]
Moving back to the mailing list.

**Comment by royeshao** [comment]
Hi Steven,
Thanks for your hints and response, it works!
Now ONL is working with Kernel 3.16.7-ckt25-OpenNetworkLinux

Thank you very much :)
Roye
