### ISSUE TITLE
no make rule error.

### ISSUE THREAD

**Issue by DataSweeper** [opennetworklinux/ONL#203]
Hi,
    I tried to build onl from scratch on my x86 machine. But I got following error.

/git/OpenNetworkLinux$ docker/tools/onlbuilder

[ ok ] Enabling additional executable binary formats: binfmt-support.
:~/git/OpenNetworkLinux$ source setup.env
Cloning into 'sm/infra'...
remote: Counting objects: 1679, done.
remote: Total 1679 (delta 0), reused 0 (delta 0), pack-reused 1679
Receiving objects: 100% (1679/1679), 439.51 KiB | 70.00 KiB/s, done.
Resolving deltas: 100% (933/933), done.
Checking connectivity... done.
Submodule path 'sm/infra': checked out 'b7974c19ed40c484f75974f4ba5975ba1ba9e1a7'
Cloning into 'sm/bigcode'...
remote: Counting objects: 3262, done.
remote: Total 3262 (delta 0), reused 0 (delta 0), pack-reused 3262
Receiving objects: 100% (3262/3262), 939.43 KiB | 59.00 KiB/s, done.
Resolving deltas: 100% (1991/1991), done.
Checking connectivity... done.
Submodule path 'sm/bigcode': checked out '9a1f1526c213fd194d44d1085fdd9a978a65af27'

~/git/OpenNetworkLinux$ apt-cacher-ng

~/git/OpenNetworkLinux$ make onl-x86

make: *** No rule to make target 'onl-x86'.  Stop.
siva-2356@siva-2356:~/git/OpenNetworkLinux$ make onl-x86 onl-ppc
make: *** No rule to make target 'onl-x86'.  Stop.

~/git/OpenNetworkLinux$

Thanks,
Siva.

**Comment by krevedkoman** [comment]
use "make amd64"

**Comment by sonoble** [comment]
@krevedkoman Thanks for catching this.
