### ISSUE TITLE
how to make a clean build for ONL

### ISSUE THREAD

**Issue by nehachat** [opennetworklinux/ONL#207]
Hello,
I made some changes in platform-config for my x86 based platform and an trying to make a clean ONL build. But it seems there is no single "make clean".
Can anybody share the steps to make a clean ONL build ?

**Comment by sonoble** [comment]
You should be able to rebuild your platform by going into the vendor directory and doing make. It will rebuild the package.

**Comment by nehachat** [comment]
I tried doing a make at following directory path: 
$ONL/packages/platforms/$vendor/
OpenNetworkLinux/packages/platforms/<$vendor>$ make clean
Makefile:1: /make/pkg.mk: No such file or directory
make: *** No rule to make target `/make/pkg.mk'.  Stop.

**Comment by sonoble** [comment]
Are you in the docker builder? onlbuilder?  and have you sourced the setup.env file?

**Comment by nehachat** [comment]
I am using onlbuilder and have sources setup.env as well.

**Comment by sholeksandr** [comment]
You can use "make rebuild" in your vendor dir.
