### ISSUE TITLE
Option 67 support for zero touch provisioning

### ISSUE THREAD

**Issue by basilsaji-rtb** [opennetworklinux/ONL#209]
Hi,

Is there a way to support handling of option 67 in the dhclent of ONL. This is needed for zero touch provisioning infrastructure. Also, is there a way to enable dhcp on an interface by default when the image is installed without manual intervention?

Regards
Basil

**Comment by jnealtowns** [comment]
Basil,

Responses inline.


On Sat, May 20, 2017 at 12:25 PM, basilsaji-rtb <notifications@github.com>
wrote:

> Hi,
>
> Is there a way to support handling of option 67 in the dhclent of ONL.
> This is needed for zero touch provisioning infrastructure.
>
Are you interested in delivering the SWI to the Loader via option 67? Or
some other file related to your application configuration during image
start?
If its the latter then I imagine you'll want a dhclient hook.


> Also, is there a way to enable dhcp on an interface by default when the
> image is installed without manual intervention?
>
Sure, by adding it to the init scripts when building the root filesystem.

Jeff
