### ISSUE TITLE
Failed to install ONL on EdgeCore 5700-96X-R01

### ISSUE THREAD

**Issue by elpamyelhsa** [opennetworklinux/ONL#211]
Open Network Installer running under ONIE.
Installer Version: Open Network Linux 89f17d8 (powerpc.all,2017.10.02.18.47,89f17d8df68f835d1341f1c083466f70da8a6f64)
Detected platform: powerpc-as5700-96x-r01

Full Console Output
[ONL.txt](https://github.com/opennetworklinux/ONL/files/1965633/ONL.txt)

> This installer does not support the powerpc-as5700-96x-**r01** platform.
> Available platforms are:
> powerpc-accton-as4600-54t-r0
> powerpc-accton-as5610-52x-r0
> powerpc-accton-as5700-96x-**r0**
> powerpc-accton-as5710-54x-r0
> powerpc-accton-as6700-32x-r0
> powerpc-accton-as6700-32x-r1
> powerpc-as4600-54t
> powerpc-as5600-52x
> powerpc-as5610-52x
> powerpc-as5710-54x-r0a
> powerpc-as5710-54x-r0b
> powerpc-as6700-32x-r0
> powerpc-dni-7448-r0
> powerpc-quanta-lb9-r0
> powerpc-quanta-lb9a-r0
> powerpc-quanta-ly2-r0
> Installation cannot continue.

**Comment by jnealtowns** [comment]
This version of ONL is no longer supported. 
Please see https://github.com/opencomputeproject/OpenNetworkLinux. 

I'm afraid there aren't any versions of the as5700-96x supported by Accton in the current version of ONL (neither r0 nor r1). 

Please submit this as a new issue https://github.com/opencomputeproject/OpenNetworkLinux/issues
