### ISSUE TITLE
Quanta LB4* Support

### ISSUE THREAD

**Issue by capveg** [opennetworklinux/ONL#39]
See https://groups.google.com/forum/#!topic/opennetworklinux/Gi9Z7XjnSdE for thread, but LB4's are cheap (going for ~100 pounds on ebay) and might be a nice starter platform for ONL.

**Comment by hekho** [comment]
I bought one of those LB4M and there is a dedicated management port.

**Comment by capveg** [comment]
Interesting.  @jnealtowns also mentioned that maybe it was only the prototype models that we have in house (read: irrelevantly old boxes) that are missing management ports.  If they really do have a management port, then it's in theory possible to port ONL to it.  Unfortunately it's probably not something we can take on ourselves just yet but if you're interested in the work, check out the PortingGuide (http://opennetlinux.org/docs/porting) to see if this is something you might be interested in doing.

**Comment by hekho** [comment]
Thanks Rob. I'll see if I can take of that.

**Comment by capveg** [comment]
@hekho Great -- mail the list if (more likely, when) you get stuck.  I don't even know if ONIE exists for the box, so I would consider starting there.  Let me know how I can help!
