### ISSUE TITLE
ORC problem with accton 5710

### ISSUE THREAD

**Issue by capveg** [opennetworklinux/ONL#62]
The orc-brcm binary is missing the platform alias from "powerpc-as5710-54x-r0b" --> "powerpc-aacton-as5710-54x-r0b".  @capveg needs to recompile and publish this (note to self).

root@onl-powerpc:~# ord -d
-bash: ord: command not found
root@onl-powerpc:~# orc -d
orc: option requires an argument -- 'd'
Invalid option 
Usage: orc [options] 
-d, --driver=DRIVER_NAME  -- ASIC driver to load ("orc_brcm.so") 
-D, --debug[=val]         -- Enable debugging (INFO)
--daemon                  -- Fork and run in background
-h, --help                -- Print this message
-i, --interface-prefix    -- Virtual interface prefix ("orc") 
-p, --dpath=path          -- Add a path to the driver search path
-P, --ports-only          -- Only create virtual ports and do TX/RX - no L3
-V, --verbose             -- Enable verbose opertations

   Default driver search path:
          Path: /usr/share/orc/drivers

   Valid Logging Levels:
          Log Level: TRACE == 0
          Log Level: DEBUG == 1
          Log Level: INFO == 2
          Log Level: WARN == 3
          Log Level: ERR == 4
          Log Level: FATAL == 5
root@onl-powerpc:~# orc -D
LOG:            options.c:142 :: Setting Debug level to DEBUG
DBG:        load_driver.c:76  :: Looking for driver at: /usr/share/orc/drivers/orc_brcm.so
LOG:        load_driver.c:79  :: Found driver at: /usr/share/orc/drivers/orc_brcm.so
linux_kernel_bde: module license 'Proprietary' taints kernel.
Disabling lock debugging due to kernel taint
01-08 20:07:16.059717 Platform 'powerpc-as5710-54x-r0b' is not supported in the current build.
Platform 'powerpc-as5710-54x-r0b' is not supported in the current build.
Aborted

**Comment by minlanyu** [comment]
@capveg 

Would you help us to fix the issue soon? We got a deadline next week and cannot set routes on the Accton switch for experiments.

**Comment by capveg** [comment]
Hi Minlan,

I sent you mail about this separately but from the previous description of what you want to do, I don't think solving this problem will actually accomplish what you want.  Also, I'm going to be traveling for the next two weeks so I don't know that this problem will get fixed in time for your deadline.  Let me see what I can do, but it looks fairly unlikely that this point :-(

**Comment by capveg** [comment]
This should be fixed now - please reopen if you find this is not the case.
