### ISSUE TITLE
ORC upstart job

### ISSUE THREAD

**Issue by nshopik** [opennetworklinux/ONL#69]
Today I've poked around in ONL and its upstart job. Since by default ONL shipped with sysv-init, besides upstart job we also need sysv-init script for ORC. So I'm not sure if it worth doing both.

@capveg thoughts?

**Comment by capveg** [comment]
@jnealtowns pointed out to me that we don't have any of the upstart startup stuff (which I completely missed) so only a sysv-init script would be useful.  So doing only the sysv script is the right thing.  If you could take a swing at that, it would be much appreciated.

**Comment by nshopik** [comment]
Yeah sure, probably could come up with simple start/stop script, as soon I solve #67
