### ISSUE TITLE
make install-ws-deps fails

### ISSUE THREAD

**Issue by bharbhi** [opennetworklinux/ONL#7]
1) I am trying to create an ONL image but unable to do so as "make install-ws-deps" fails.

2) "make install-host-deps" & "mkws -a amd64 ws.amd64" is succesfull and see following outside the workspace created

iso0      Link encap:Ethernet  HWaddr 6a:5c:d3:79:94:b4
          inet addr:10.198.0.0  Bcast:0.0.0.0  Mask:255.255.255.254
          inet6 addr: fe80::685c:d3ff:fe79:94b4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:40 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:648 (648.0 B)  TX bytes:7325 (7.3 KB)

3) Was able to ping from inside workspace to 10.198.0.0 and 8.8.8.8 

4) But /etc/resolv.conf is empty inside the workspace. I tried manually editing it but it did not change.

5) Out the workspace, /etc/network/interfaces has following entry

auto eth0
iface eth0 inet static
        address 10.0.0.9
        netmask 255.0.0.0
        network 10.0.0.0
        broadcast 10.255.255.255
        gateway 10.0.0.254
        # dns-* options are implemented by the resolvconf package, if installed
        dns-nameservers 8.8.8.8
        dns-search ubuntu-1.xxx.com

6) I manually edited /etc/resolv.conf outside the workspace.

**Comment by capveg** [comment]
This issue should be gone with the new docker based build system -- yay!
