### ISSUE TITLE
ORC Segmentation faults on lb9

### ISSUE THREAD

**Issue by capveg** [opennetworklinux/ONL#78]
root@onl-powerpc:~# orc -D=0
LOG:            options.c:142 :: Setting Debug level to TRACE
DBG:        load_driver.c:76  :: Looking for driver at: /usr/share/orc/drivers/orc_brcm.so
LOG:        load_driver.c:79  :: Found driver at: /usr/share/orc/drivers/orc_brcm.so
Segmentation fault

As reported by @nshopik .

**Comment by nshopik** [comment]
From commits I don't see any changes related to ORC recently. And from what I see in segmenatation fault it appears always crash in aim_pvs_stderr(), some calls to aim_pvs()?
https://github.com/Broadcom-Switch/of-dpa/tree/master/src/ofagent/indigo/submodules/infra/modules/AIM/module/inc/AIM

We probably need to build ORC with debug symbols if this doesn't ring bell.

**Comment by capveg** [comment]
My guess is that the bug in ORC is in the closed source binary part (the
orc-brcm.so), which unfortunately we can't distribute with debugging
symbols.  I'll try to take a swing at it and hopefully it's something
trivial.

Thanks for looking into it.

- Rob
.

**Comment by nshopik** [comment]
I hope broadcom sooner realize that is bad for community and their own business. Even Microsoft allow me debug symbols since dawn of windows, which is help me lot of time to diagnose weird BSODs.

Thanks Rob, will wait for your update

**Comment by capveg** [comment]
Fwiw, I wouldn't blame Broadcom on this - turns out it's an internal API change that I missed and I'll have to do some refactoring.  Long story short, this isn't a quick fix and it may be a few more days :-/

**Comment by nshopik** [comment]
@capveg Rob any updates on fix?

**Comment by capveg** [comment]
I've been working on this and should have it posted in the next day or
two.  Because some of the internal APIs got updated, I had to update a
bunch of other things as well.  And then beef up the debugging and testing
infrastructure to make sure it all worked.  Good news is that ORC is
getting a debugging CLI (lots of infrastructure for this already in the
bigcode repo; almost no new code), but the bad news is that it's taken me a
while.

Thanks for your patience.

**Comment by capveg** [comment]
I've just posted new code and new binary driver for ORC.  Minimally, it doesn't core dump any more and appears to work correctly.  The next thing I'm working on is a testing harness so we can get some automated testing in place to work ORC through its paces.  Also, by my own hand testing, it seems like the SFP code is still working for lb9 :-)

Take a swing and let me know if you find any issues.

**Comment by nshopik** [comment]
Thanks Rob, is there any pre-build installers ready? I've never bother to compile ONL after my first attempt failed.

**Comment by capveg** [comment]
Just now posted them.

**Comment by nshopik** [comment]
Looks good, no more segfaults and more verbose which is nice.

**Comment by capveg** [comment]
Fixed - closing.
