### ISSUE TITLE
onlpdump -r doesn't print/decode SFP info -- needs improvement

### ISSUE THREAD

**Issue by capveg** [opennetworklinux/ONL#79]
As reported by @nshopik 

If you run onlpdump (without the -r option), it raw dumps all of the ONLP data, mostly of use for programmers.  It also includes a hex dump of SFP info from the eeprom.  

But, when you run with -r, e.g., the "human readable" dump, it does not include the any SFP info (decoded or otherwise).  It would be nice to decode the SFP eeprom data which includes nice manufacturer and product name ASCII descriptions.

One point: @jnealtowns mentioned that the SFP parsing routines are already in the ONLP libraries so in theory the pretty print version of the SPF code could be done by you if you want.

**Comment by capveg** [comment]
FYI, rough plan for onlpdump (that I'm working on with orc -- correlated code):
* rename onlpdump to onlptool. 
* keep existing (statically linked) onlptool in the per-platform directories (for debugging) 
* create a dynamically linked onlptool that installs from the onlp component
    * add SFP decoding functionality to it along with other human nicities


So, in short, there is some refactoring that's going to happen as well.

**Comment by alexanderturner** [comment]
Did this happen?

**Comment by jnealtowns** [comment]
Everything other than renaming onlpdump -> onlptool (which is probably
still a good idea).

The multi-platform dynamic version is called onlpd.

You can decode the SFP inventory with onlpd -S

root@as5712-1:~# *onlpd -S*
Port  Type            Media   Status  Len    Vendor            Model
      S/N
----  --------------  ------  ------  -----  ----------------
 ----------------  ----------------
   0  NONE
   1  NONE
   2  NONE
   3  NONE
   4  NONE
   5  NONE
   6  NONE
   7  NONE
   8  10GBASE-CR      Copper          1m     3M
 1410-P17-00-1.00  Y10F420263
   9  10GBASE-CR      Copper          1m     3M
 1410-P17-00-1.00  Y10F420157
  10  10GBASE-CR      Copper          1m     3M
 1410-P17-00-1.00  Y10F420253
  11  10GBASE-CR      Copper          1m     3M
 1410-P17-00-1.00  Y10F420351
  12  10GBASE-CR      Copper          1m     3M
 1410-P17-00-1.00  Y10F420188
  13  10GBASE-CR      Copper          1m     3M
 1410-P17-00-1.00  Y10F420121
  14  10GBASE-CR      Copper          1m     3M
 1410-P17-00-1.00  Y10F420220
  15  10GBASE-CR      Copper          1m     3M
 1410-P17-00-1.00  Y10F420120
  16  NONE
  17  NONE
  18  NONE
  19  NONE
  20  NONE
  21  NONE
  22  NONE
  23  NONE
  24  NONE
  25  NONE
  26  NONE
  27  NONE
  28  NONE
  29  NONE
  30  NONE
  31  NONE
  32  NONE
  33  NONE
  34  NONE
  35  NONE
  36  NONE
  37  NONE
  38  NONE
  39  NONE
  40  NONE
  41  NONE
  42  NONE
  43  NONE
  44  NONE
  45  NONE
  46  NONE
  47  NONE
  48  40GBASE-CR4     Copper          1m     3M Company
 9QA0-111-12-1.00  V10F8232
  49  40GBASE-CR4     Copper          1m     3M Company
 9QA0-111-12-1.00  V10F8153
  50  NONE
  51  NONE
  52  NONE
  53  NONE
root@as5712-1:~#


On Thu, Jul 27, 2017 at 11:43 PM, Alexander Turner <notifications@github.com
