### ISSUE TITLE
LLDP packets not punted to CPU

### ISSUE THREAD

**Issue by nshopik** [opennetworklinux/ONL#92]
LLDP packets forwarded instead of punted to CPU. This is probably because mac addresses 01:80:c2:00:00:0e, 01:80:c2:00:00:03, 01:80:c2:00:00:00 not considered as local.

**Comment by capveg** [comment]
This will be a good test to setup in my testing harness.  Give me a few days to hack it up and I'll try to post a fix.

**Comment by capveg** [comment]
I believe this is fixed with orc-brcm 0.3.1 -- please test and reopen if I'm wrong.
