### ISSUE TITLE
make onl-x86 failed because of implicit declaration of function ‘i2c_smbus_read_byte_data’

### ISSUE THREAD

**Issue by larryming** [opennetworklinux/ONL#93]
I want to build ONL for x86-64 and follow standard steps as official site doc.
It failed as following log:
    Compiling[ release ]: onlplib::onie.c
    Compiling[ release ]: onlplib::onlplib_config.c
    Compiling[ release ]: onlplib::onlplib_enums.c
    Compiling[ release ]: onlplib::onlplib_log.c
/home/larry/works/ONL/submodules/onlp/modules/onlplib//module/src//i2c.c: In function ‘onlp_i2c_read’:
/home/larry/works/ONL/submodules/onlp/modules/onlplib//module/src//i2c.c:100:9: error: implicit declaration of function ‘i2c_smbus_read_byte_data’ [-Werror=implicit-function-declaration]
/home/larry/works/ONL/submodules/onlp/modules/onlplib//module/src//i2c.c: In function ‘onlp_i2c_write’:
/home/larry/works/ONL/submodules/onlp/modules/onlplib//module/src//i2c.c:133:9: error: implicit declaration of function ‘i2c_smbus_write_byte_data’ [-Werror=implicit-function-declaration]
/home/larry/works/ONL/submodules/onlp/modules/onlplib//module/src//i2c.c: In function ‘onlp_i2c_readw’:
/home/larry/works/ONL/submodules/onlp/modules/onlplib//module/src//i2c.c:187:5: error: implicit declaration of function ‘i2c_smbus_read_word_data’ [-Werror=implicit-function-declaration]
/home/larry/works/ONL/submodules/onlp/modules/onlplib//module/src//i2c.c: In function ‘onlp_i2c_writew’:
/home/larry/works/ONL/submodules/onlp/modules/onlplib//module/src//i2c.c:206:5: error: implicit declaration of function ‘i2c_smbus_write_word_data’ [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make[6]: *** [build/powerpc-linux-gnu/obj//home/larry/works/ONL/submodules/onlp/modules/onlplib//module/src//i2c.o] Error 1
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [component] Error 2
make[4]: *** [deb] Error 2
make[3]: *** [deb] Error 2
make[2]: *** [deb] Error 2
make[2]: Leaving directory `/home/larry/works/ONL/components/powerpc/onlp/onlp-powerpc-quanta-ly2-r0'
Traceback (most recent call last):
  File "/home/larry/works/ONL/tools/onlpkg.py", line 287, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/larry/works/ONL/tools/onlpkg.py", line 157, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/larry/works/ONL/components/powerpc/onlp/onlp-powerpc-quanta-ly2-r0', 'deb')' returned non-zero exit status 2
make[1]: *** [component-deps] Error 1
make[1]: Leaving directory `/home/larry/works/ONL/builds/components'
make: *** [all-components] Error 2
(iso1:ws.amd64)larry@larry-VirtualBox:~/works/ONL$ 

What is wrong with my build?
Any help will be very thankful.

Thanks in advance!
Larry Ming

**Comment by capveg** [comment]
This is fixed with the new docker build system.  Please open again if you're still having problems.
